<?php $this->loadPartial('header'); ?>

        <div class="jumbotron">
            <h1>The <strong>Gria Framework</strong> is a no-fuss, flexible PHP web application framework that enables developers to build web-based software quickly.</h1>
        </div>

        <div class="splash">

        </div>

        <div class="actions">
            <button class="btn btn-default">Download 1.0.0 <i class="fa fa-download"></i></button> <button class="btn btn-default">View the docs <i class="fa fa-book"></i></button>
        </div>

<?php $this->loadPartial('footer'); ?>