<hr>
<footer>
    <p>Copyright &copy; 2013-<?php echo date('Y'); ?> Gria Solutions, LLC. All rights reserved.</p>
</footer>
</div>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/assets/lib/jquery/jquery.min.js"><\/script>')</script>
<script src="/assets/lib/bootstrap/bootstrap.min.js"></script>
<script src="/assets/js/plugins.js"></script>
<script src="/assets/js/main.js"></script>
</body>
</html>