<!DOCTYPE html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Gria Framework Documentation</title>
    <meta name="description" content="This application is powered by the Gria Framework.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/assets/css/main.css">
    <script src="/assets/lib/modernizr/modernizr.js"></script>
</head>
<body>

<div class="container">

    <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Gria/<strong>Framework</strong></a>
            </div>
            <div class="navbar-collapse collapse pull-right">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#">Overview</a></li>
                    <li><a href="#">Getting Started</a></li>
                    <li><a href="#">Tutorials</a></li>
                    <li><a href="#">Guides</a></li>
                    <li><a href="#">API Reference</a></li>
                    <li><a href="#">About</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
    </div>

    <div class="container">