<!DOCTYPE html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Gria Framework Documentation</title>
    <meta name="description" content="This application is powered by the Gria Framework.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/assets/css/main.css">
    <script src="/assets/lib/modernizr/modernizr.js"></script>
</head>
<body>
<div id="wrap" class="container">
    <!--[if lt IE 8]>
    <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <div class="masthead">
        <h3 class="muted">Gria/<strong>Framework</strong></h3>
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <ul class="nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#">The Basics</a></li>
                        <li><a href="#">Tutorials</a></li>
                        <li><a href="#">Guides</a></li>
                        <li><a href="#">API Reference</a></li>
                        <li><a href="#">About</a></li>
                    </ul>
                </div>
            </div>
        </div><!-- /.navbar -->
    </div>

    <div id="main" role="main" class="container">